# Generated by Django 2.0.5 on 2018-07-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dear_diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrySummarry',
            fields=[
            ],
            options={
                'verbose_name': 'Entry Summary',
                'verbose_name_plural': 'Entries Summary',
                'proxy': True,
                'indexes': [],
            },
            bases=('dear_diary.entry',),
        ),
    ]
