# Generated by Django 2.0.5 on 2018-07-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dear_diary', '0002_entrysummarry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
