# Generated by Django 2.0.5 on 2018-07-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('made_on', models.DateField()),
            ],
        ),
    ]
